### ISSUE TITLE
timepicker-bs4 formatting issue on iPhone

### ISSUE THREAD

**Issue by MicJarek** [lesilent/timepicker-bs4#4]
The timepicker display works great in browsers on desktop Windows and Android, but when previewed in Safari on an iPhone, there seems to be a formatting issue. There is too much space on either side of the colon, between the hours and minutes display (see image). 
![timepicker-bs4- (display Issue on iPhone)-sm](https://github.com/lesilent/timepicker-bs4/assets/17038597/8a8a1604-8d9a-47ae-95e2-808228a8d879)

I'm guessing apple is not respecting all the table formatting being used to display the elements?

**Comment by lesilent** [comment]
This should be fixed now in the newest release.

**Comment by MicJarek** [comment]
Well... it doesn't seem to be completely fixed. Although now more evenly spaced, it would be great if the spacing was condensed just like it is on Android and desktop browsers. (see attached images)

Also, I noticed that you added the 'dark' background support. So now on desktop and iPhone it still looks 'light', but on Android, it defaults to 'dark'. Is there a flag I can set to force it to always be the 'light' mode? It really looks strange when this is the only popup that displays in 'dark' mode in the application.

Tks... :)
![timepicker-bs4- (display Issue on Android - 2023-10-16)-sm](https://github.com/lesilent/timepicker-bs4/assets/17038597/ded9c20e-1b18-4542-8b1b-83ddd26ee10b)
![timepicker-bs4- (display Issue on iPhone - 2023-10-16)-sm](https://github.com/lesilent/timepicker-bs4/assets/17038597/9592b4e7-7c5e-47ed-a217-4c61f59f7c35)

**Comment by lesilent** [comment]
Can you try the newest version? I believe it should fix the spacing issue on the iPhone and has a "theme" option for forcing light mode.  By default, the theme is based on the mode that the browser/phone is set to. Is your browser/phone perhaps set to dark mode?

**Comment by MicJarek** [comment]
Yes, the latest version fixed the iPhone spacing issue. But... the theming is still not working properly. If I set the theme to 'light' or 'dark', I get an error:
timepicker-bs4.js?v=SGrbRg0duqpRiOHhrV1rc_myNurZWe4UbO177Ls-9HQ:33  Uncaught ReferenceError: light is not defined

And you are correct that my Android theme mode was/is set to dark mode. The issue is: the entire app is displayed in light mode and therefore it will look odd to users who also have the dark theme set (whether Android or browser theme), and ONLY see the timepicker in dark mode. So forcing the mode via code is a great addition.

**Comment by lesilent** [comment]
Are you passing light as a variable instead of a string?

Doing this:  `.timepicker({ theme: light });`

When it should be this: `.timepicker({ theme: 'light' });`

**Comment by MicJarek** [comment]
Ooops... my bad. That's what it was. Tks. It's looking awesome now!

And since we're talking about configuration, have you thought about adding more options to customize? 

As you can see from the image, I had to change a few things in the .js file to be more consistent with the app. 
1) I added form-control-sm to 3 of the fields (since all my edit <input> fields/buttons are sm)
2) I changed the button look by changing the size, text, order, and made the cancel button btn-primary (since there are also comment 'edit' buttons that reflect this)
3) Commented out the 'jQuery('#' + input_id + '-picker-content').find('.hour-input').select()' code that sets focus when the picker first appears. The reason I changed this was because there is a mask on the field that users can type the time directly into the field and therefore my logic was that it is unnecessary for them to actually click the button to display the picker and then edit the time. Besides, on mobiles, the keyboard automatically pops up because of the .select(), and that seems too flashy.

Anyway, just a few thoughts and reasoning behind my changes. Otherwise, the date and time pickers work great now. Tks... :)
![timepicker-bs4- (final display on Android - 2023-10-17)-sm](https://github.com/lesilent/timepicker-bs4/assets/17038597/57d428b5-14e1-440d-8c88-8092d61a6a03)

**Comment by lesilent** [comment]
A concern with adding more options to customize the appearance is that there are so many possible things to customize (eg. background color, color, icons, text, input sizes, etc.) to the point where the code can get really bogged down. But, if there's enough interest from others for a particular customization and it's reasonable enough to implement, then I'll reconsider it.

Having said that, the newest commit includes the following changes that might be a little relevant for some of the customizations that you mentioned:
1. Switched the default theme from auto to light since most users don't have sites that automatically change their theme to match the browser's theme.
2. Replaced the text on the buttons with icons albeit with same different colors.
3. Made the setting focus on the input only applicable on screens wider than 575 pixels since I imagine desktop users would want to use the keyboard while also preventing the keyboard from popping up on mobile.

**Comment by MicJarek** [comment]
I totally agree with everything you said, and nice enhancements to the latest version. It's not easy to be accommodating to 'everyone' so I was simply throwing things out there based on what I faced and had to adjust the code accordingly. Besides the color scheme, the difference between the datepicker and the timepicker is that the latter has the 2 buttons which obviously should be representative of the application (and hence why I made the adjustments). But all in all, both pickers work great now so kudos to you for a great job.

And just so you know (relating to your no.3 above), my app also uses masks on both the date 'i.e. mm/dd/yyyy' and time fields to allow the user to enter the date or time directly by simply clicking into the input field (when the button next to the input field is clicked, that is when the picker pops up). And that is why I commented out the .select() feature. But I'm sure everyone will have their own requirements, so I completely get why there is only so many options you can implement.

Anyway, great work again and thanks for all your help. Cheers...😊
